apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hotel-system
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: hotel-backend
          image: eli0504167101/hotel-backend:79
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongo-url
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20