apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hotel-system
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: hotel-backend
        image: eli0504167101/hotel-backend:41
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongo-url
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongo-password
        - name: BACKEND_URL # תוסיף את זה
          value: "localhost:8080" # בתוך ה-Backend עצמו הוא יכול לפנות ל-localhost
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: / 
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10