apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: hotel-frontend
        image: hotel-frontend:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend-service:3000" # השירות שיקשר בין ה-Frontend ל-Backend