apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: hotel-system
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: hotel-frontend
        image: eli0504167101/hotel-frontend:77
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        # כאן הפרובים צריכים להיות, בתוך ה-container
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20